# Generated by Django 3.2.13 on 2023-01-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='diplom_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Общая'), (2, 'Теория'), (3, 'Практика')], default=1),
        ),
        migrations.AddField(
            model_name='demand',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Казахский'), (2, 'Русский'), (3, 'Английский')], default=1),
        ),
    ]
