# Generated by Django 3.2.13 on 2023-01-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20230118_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddistribution',
            name='prepayment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
