# Generated by Django 3.2.13 on 2023-01-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_demanddistribution_prepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='diplom_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Общая'), (2, 'Теория'), (3, 'Практика')], default=True, null=True),
        ),
    ]
