# Generated by Django 3.2.13 on 2023-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_alter_demand_diplom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='diplom_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Общая'), (2, 'Теория'), (3, 'Практика')], default=1),
        ),
    ]
