# Generated by Django 3.2.13 on 2023-01-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_alter_demand_diplom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='is_distribution',
            field=models.BooleanField(default=False),
        ),
    ]
