# Generated by Django 3.2.13 on 2023-01-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_demand_is_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='is_distribution',
            field=models.BooleanField(default=True),
        ),
    ]
