# Generated by Django 3.2.13 on 2023-01-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_alter_demand_is_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddistribution',
            name='is_expert_selected',
            field=models.BooleanField(default=False),
        ),
    ]
