# Generated by Django 3.2.13 on 2023-01-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_demanddistribution_is_expert_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanddistribution',
            name='is_expert_selected',
        ),
        migrations.AddField(
            model_name='demand',
            name='is_expert_selected',
            field=models.BooleanField(default=False),
        ),
    ]
