# Generated by Django 3.2.13 on 2023-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_demanddistribution_is_expert_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcompletedfile',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
