# Generated by Django 4.1 on 2023-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0016_alter_demanddistribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanddistribution',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ожидание'), (2, 'Отклик'), (3, 'Ожидание оплаты'), (4, 'Заказ принят'), (5, 'Заказ оплачено')], default=1),
        ),
    ]
