# Generated by Django 3.2.4 on 2023-03-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0017_alter_demanddistribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanddistribution',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demanddistribution',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
