# Generated by Django 4.1.1 on 2023-01-09 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_task_management', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedayrating',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employeedayrating',
            name='recomend_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не работал'), (2, 'Очень плохо'), (3, 'Плохо'), (4, 'Хорошо'), (5, 'отлично')], default=1),
        ),
        migrations.AlterField(
            model_name='employeedayrating',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Не работал'), (2, 'Очень плохо'), (3, 'Плохо'), (4, 'Хорошо'), (5, 'отлично')], null=True),
        ),
    ]
