# Generated by Django 4.1.1 on 2023-01-09 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_task_management', '0003_employeedayrating_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedayrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
