# Generated by Django 4.1.4 on 2023-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_task_management", "0005_employeedayrating_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарии"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Не выполнен"), (2, "Выполнен"), (3, "Отказ")],
                default=1,
                verbose_name="Статус",
            ),
        ),
    ]
