# Generated by Django 4.0.3 on 2023-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=75, unique=True, verbose_name='email address'),
        ),
    ]
